### ISSUE TITLE
How long will the paymasterAndData expire?

### ISSUE THREAD

**Issue by PengDeng-Cyber** [base-org/paymaster#20]

**Comment by mdehoog** [comment]
Currently there is no expiration, but that may change in the future, or have different values on different chains.

You can generally assume that bytes 20 to 84 (exclusive) contain two ABI encoded `uint48`s that represent the `validUntil` and `validAfter` values. See https://github.com/base-org/paymaster/blob/fc47a5f5ae1a3d9eca016c267d1ca5bce0a2cb52/src/Paymaster.sol#L88.
